name: Tests
on:
  push:
  workflow_call:

jobs:
    build_publish:
        runs-on: macos-14
        permissions:
          packages: write
        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - uses: benjlevesque/short-sha@v3.0
            id: short-sha
            with:
              length: 7

          - name: Setup JDK 21
            uses: actions/setup-java@v4
            with:
              java-version: 21
              distribution: 'temurin'

          - name: Setup Gradle
            uses: gradle/actions/setup-gradle@v3

          - run: chmod +x ./gradlew

          - name: Test
            run: ./gradlew test:test